### ISSUE TITLE
incompatibility: app does not work if Spotify is installed on the same device

### ISSUE THREAD

**Issue by davemee** [CMDT/gaddum_app#24]
Unable to confirm fully unless App Store login/Play store log in is set up on devices

**Comment by davemee** [comment]
Further to this: as of 2019-11-12 11:30 the `cordova-spotify-plugin' does not build on iOS due to the moving the of the Spotify codebase on Github. This has been raised as an issue at https://github.com/Festify/cordova-spotify-oauth/issues/28 however Laurie thinks this can be circumvented by refactoring authentication to use web-native methods.

**Comment by coopsatwork** [comment]
Fixed in 8090b2b12c86ccbc6dcc0d8498edd43b66a69c30

**Comment by coopsatwork** [comment]
Wrong fix :-(

**Comment by coopsatwork** [comment]
Will be fixed by workaround to #38

**Comment by coopsatwork** [comment]
https://github.com/CMDT/gaddum_app/commit/ccbda354e29e8a08b638d4bfd49d7a1d9f0c7782

fixed in 0.0.3
