### ISSUE TITLE
On launch, 'Friends' tab has incorrect menu

### ISSUE THREAD

**Issue by davemee** [CMDT/gaddum_app#36]
When launching the app the first time and presented with the 'Friends' section, the menu at the bottom is populated with items from the 'Playlist' section, rather than the 'Friends' section

*Expected*
'Add friend'

*Issue*
has 'Import Playlists', 'Create Playlist'

**Comment by coopsatwork** [comment]
Should this be in the Trello board? This is not in released code yet.
