### ISSUE TITLE
'Add Friend' should not be an available menu option if you do not have a valid profile

### ISSUE THREAD

**Issue by davemee** [CMDT/gaddum_app#39]
Even better, maybe a new menu item 'Set up Profile' (which goes to the profile section) should appear in its stead

**Comment by coopsatwork** [comment]
Should this be in the Trello board? This is not in released code yet.

**Comment by coopsatwork** [comment]
fixed in bd38406d1b9bb4f9eeeea8397ffbf80f263e673a
