### ISSUE TITLE
Adding songs from Browse to a Playlist fails

### ISSUE THREAD

**Issue by davemee** [CMDT/gaddum_app#4]
## What Happens

New empty playlist created in application. Adding a track found in 'browse' brings up 'add to playlist' but at 'Are You Sure'? pressing 'Add' generates error:

` 'TypeError: namedIdentifierTrack.getId is not a function at asyncAssociatePlaylistAndTrack (data_api.service.js:1069)'`

**Comment by coopsatwork** [comment]
same as #22
